linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: gh-review-task
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # Don't use deprecated linters
  disable:
    - maligned
    - interfacer
    - scopelint

run:
  deadline: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines of comments
    - linters:
        - lll
      source: "^//.*$"

  max-issues-per-linter: 0
  max-same-issues: 0